apiVersion: apps/v1
kind: Deployment
metadata:
 name: user-service
 namespace: go-microservices
spec:
 replicas: 2
 selector:
   matchLabels:
     app: user-service
 template:
   metadata:
     labels:
       app: user-service
   spec:
     containers:
       - name: user-service
         image: gauss23/user-service:latest
         imagePullPolicy: Never
         ports:
           - containerPort: 8083
         resources:
           requests:
             memory: "128Mi"
             cpu: "100m"
           limits:
             memory: "256Mi"
             cpu: "200m"
         livenessProbe:
           httpGet:
             path: /health
             port: 8083
           initialDelaySeconds: 30
           periodSeconds: 10
         readinessProbe:
           httpGet:
             path: /health
             port: 8083
           initialDelaySeconds: 5
           periodSeconds: 5